name: CI

on:
  push:
    branches: [ main, qa, dev ]
  pull_request:
    branches: [ main, qa, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Set up Oracle JDK 21
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 21

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build
        run: ./mvnw -q -DskipTests package

      - name: Test
        run: ./mvnw -q -DskipTests=false test

      - name: Upload surefire reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
